accessKey_id = ""
accessKey_secret = ""
account_id = ""
allow_route_list = [
  "/v1.0/me/drive",
  "/v1.0/me/drive/root/children",
  "/v1.0/me/drive/items/{}",
  "/v1.0/me/drive/root:/{}",
  "/v1.0/me/drive/root:/{}:/children",
  "/v1.0/drives/{}/root/children",
  "/v1.0/drives/{}/items/{}/children",
  "/v1.0/drives/{}/root:/{}:/children",
]
auth_file_name = "Microsoft-Graph-Auth.json"
author = "https://github.com/lisonge"
bucket = ""
client_id = ""
client_secret = ""
redirect_uri = ""
region = "cn-hongkong"
